# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for iplookup
# Check the documentation at https://goreleaser.com

version: 2

project_name: iplookup

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: iplookup
    main: ./main.go
    binary: iplookup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

archives:
  - id: iplookup
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Others'
      order: 999

release:
  github:
    owner: gofika
    name: iplookup
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## iplookup v{{.Version}}
    
    Fast and simple IP address lookup toolË‡
  footer: |
    ---
    
    **Full Changelog**: https://github.com/gofika/iplookup/compare/{{ .PreviousTag }}...{{ .Tag }}

homebrew_casks:
  - repository:
      owner: gofika
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    name: iplookup
    homepage: "https://github.com/gofika/iplookup"
    description: "Fast and simple command-line IP address lookup tool"
    license: "MIT"

nfpms:
  - id: packages
    package_name: iplookup
    homepage: https://github.com/gofika/iplookup
    description: "Fast and simple command-line IP address lookup tool"
    maintainer: Gofika <github.com/gofika>
    license: MIT
    vendor: Gofika
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

# Docker builds with multi-platform support
dockers:
  - image_templates:
      - "ghcr.io/gofika/iplookup:{{ .Tag }}-amd64"
      - "ghcr.io/gofika/iplookup:latest-amd64"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/gofika/iplookup:{{ .Tag }}-arm64"
      - "ghcr.io/gofika/iplookup:latest-arm64"
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"

# Create manifest lists for multi-platform support
docker_manifests:
  - name_template: "ghcr.io/gofika/iplookup:{{ .Tag }}"
    image_templates:
      - "ghcr.io/gofika/iplookup:{{ .Tag }}-amd64"
      - "ghcr.io/gofika/iplookup:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/gofika/iplookup:latest"
    image_templates:
      - "ghcr.io/gofika/iplookup:latest-amd64"
      - "ghcr.io/gofika/iplookup:latest-arm64"